package databproject;
import databproject.AdminPage;
import databproject.Bill;
import databproject.Employee;
import databproject.LoginPage;
import databproject.PharmacyAPI;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class ManagerPage extends javax.swing.JFrame {
    static Connection con;
    Bill billobj;    
    PharmacyAPI pharma = PharmacyAPI.getInstance();
    Employee empobj = new Employee(pharma);
    static LoginPage loginp = new LoginPage();
    /**
     * Creates new form ManagerPage
     */
    public ManagerPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empname = new javax.swing.JTextField();
        empssn = new javax.swing.JTextField();
        empsalary = new javax.swing.JTextField();
        empmanid = new javax.swing.JTextField();
        empPN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        empBid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 142, 214, -1));
        getContentPane().add(empssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 177, 214, -1));

        empsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(empsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 212, 214, -1));
        getContentPane().add(empmanid, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 247, 214, -1));
        getContentPane().add(empPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 141, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("SSN:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 176, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Salary:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 211, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Manager ID:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 246, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Phone Number:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 356, -1, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 412, -1, -1));

        jButton3.setText("Update Salary");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 384, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SSN", "Name", "Salary", "Manager SSN", "Branch id"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, 373, 410));

        jButton4.setText("Show Employees");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 87, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Branch ID:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));
        getContentPane().add(empBid, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 210, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Manage Employees:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jButton13.setText("LogOut");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MenuBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empsalaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if (!empssn.getText().equals("") || !empname.getText().equals("") || !empBid.getText().equals("") || !empsalary.getText().equals("")||!empmanid.getText().equals("") || !empPN.getText().equals("")) {
        try {
            empobj.insert(Integer.parseInt(empssn.getText()), empname.getText(), Integer.parseInt(empsalary.getText()), Integer.parseInt(empBid.getText()), Integer.parseInt(empmanid.getText()), empPN.getText());
            JOptionPane.showMessageDialog(this, "Employee has been added successfully!");
        } catch (SQLException ex) {
            if (ex instanceof SQLIntegrityConstraintViolationException) {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage() + "\nPossible foreign key constraint violation.");
            } else {
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please insert all fields!");
    }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0); // Clear existing rows

try {
    // Get data from the database using the selectall method
    ArrayList<ArrayList<String>> data = empobj.selectall();

    // Update the table model on the EDT
    
        for (ArrayList<String> row : data) {
            model.addRow(row.toArray());
        }
    
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error loading data from the database.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try {
            empobj.updatesalary(Integer.parseInt(empssn.getText()), Integer.parseInt(empsalary.getText()));
            JOptionPane.showMessageDialog(this, "Salary has been updated successfully!");
        }catch (NullPointerException e){
         JOptionPane.showMessageDialog(this, "You must enter SSN field and salary Field");
        }   catch (SQLException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
    String ssnText = empssn.getText();
    String manid=empmanid.getText();
    String emdbrn=empBid.getText();
    if (ssnText != null && !ssnText.isEmpty() && manid != null && !manid.isEmpty()&& emdbrn != null && !emdbrn.isEmpty()) {
        int ssn = Integer.parseInt(ssnText);
        empobj.deletePN(empssn.getText());
        empobj.delete(ssn);
            JOptionPane.showMessageDialog(this, "Employee has been removed successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "You must insert SSN,Manager ID,and Branch ID fields");
        }
    } catch (SQLException ex) {
        Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid SSN format. Please enter a valid integer.");
    }          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        this.setVisible(false);
        loginp.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empBid;
    private javax.swing.JTextField empPN;
    private javax.swing.JTextField empmanid;
    private javax.swing.JTextField empname;
    private javax.swing.JTextField empsalary;
    private javax.swing.JTextField empssn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
